package MainJCashApp;

import java.awt.Toolkit;

/**
 *
 * @author "Jahnreil J. Amarillento"
 */
public class BalanceInquiry extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public BalanceInquiry() {
        initComponents();
        setIconLogo();
        
        BankAccounts accs = new BankAccounts();
        balanceOutput.setText(String.valueOf(accs.getAcct1().getSavings()));
    }

    public void setIconLogo() {
            setIconImage(Toolkit.getDefaultToolkit().getImage("src/main/java/Resources/JCash1.png"));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenuPanel = new javax.swing.JPanel();
        balanceLabel = new javax.swing.JLabel();
        balanceOutput = new javax.swing.JLabel();
        doneBtn = new javax.swing.JButton();
        mainMenuTitlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jCashLogoMM = new javax.swing.JLabel();
        southSpacerPanel = new javax.swing.JPanel();
        westSpacerPanel = new javax.swing.JPanel();
        eastSpacerPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainMenuPanel.setBackground(new java.awt.Color(45, 36, 36));
        mainMenuPanel.setPreferredSize(new java.awt.Dimension(650, 250));

        balanceLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        balanceLabel.setForeground(new java.awt.Color(224, 192, 151));
        balanceLabel.setText("Balance: ");

        balanceOutput.setBackground(new java.awt.Color(45, 36, 36));
        balanceOutput.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        balanceOutput.setForeground(new java.awt.Color(224, 192, 151));

        doneBtn.setBackground(new java.awt.Color(92, 61, 46));
        doneBtn.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        doneBtn.setForeground(new java.awt.Color(224, 192, 151));
        doneBtn.setText("Done");
        doneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainMenuPanelLayout = new javax.swing.GroupLayout(mainMenuPanel);
        mainMenuPanel.setLayout(mainMenuPanelLayout);
        mainMenuPanelLayout.setHorizontalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainMenuPanelLayout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(doneBtn))
                    .addGroup(mainMenuPanelLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(balanceLabel)
                        .addGap(42, 42, 42)
                        .addComponent(balanceOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(173, 173, Short.MAX_VALUE))
        );
        mainMenuPanelLayout.setVerticalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(balanceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(balanceOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                .addComponent(doneBtn)
                .addGap(62, 62, 62))
        );

        getContentPane().add(mainMenuPanel, java.awt.BorderLayout.CENTER);

        mainMenuTitlePanel.setBackground(new java.awt.Color(45, 36, 36));
        mainMenuTitlePanel.setMinimumSize(new java.awt.Dimension(300, 300));
        mainMenuTitlePanel.setLayout(new java.awt.BorderLayout());

        titleLabel.setBackground(new java.awt.Color(45, 36, 36));
        titleLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(224, 192, 151));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Balance Inquiry");
        titleLabel.setPreferredSize(new java.awt.Dimension(100, 100));
        mainMenuTitlePanel.add(titleLabel, java.awt.BorderLayout.CENTER);

        jCashLogoMM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCashLogoMM.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/730396842197778485/1022840337212911666/JCashLogoFull.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        mainMenuTitlePanel.add(jCashLogoMM, java.awt.BorderLayout.NORTH);

        getContentPane().add(mainMenuTitlePanel, java.awt.BorderLayout.NORTH);

        southSpacerPanel.setBackground(new java.awt.Color(184, 92, 56));

        javax.swing.GroupLayout southSpacerPanelLayout = new javax.swing.GroupLayout(southSpacerPanel);
        southSpacerPanel.setLayout(southSpacerPanelLayout);
        southSpacerPanelLayout.setHorizontalGroup(
            southSpacerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        southSpacerPanelLayout.setVerticalGroup(
            southSpacerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        getContentPane().add(southSpacerPanel, java.awt.BorderLayout.PAGE_END);

        westSpacerPanel.setBackground(new java.awt.Color(45, 36, 36));

        javax.swing.GroupLayout westSpacerPanelLayout = new javax.swing.GroupLayout(westSpacerPanel);
        westSpacerPanel.setLayout(westSpacerPanelLayout);
        westSpacerPanelLayout.setHorizontalGroup(
            westSpacerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        westSpacerPanelLayout.setVerticalGroup(
            westSpacerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        getContentPane().add(westSpacerPanel, java.awt.BorderLayout.LINE_END);

        eastSpacerPanel.setBackground(new java.awt.Color(45, 36, 36));

        javax.swing.GroupLayout eastSpacerPanelLayout = new javax.swing.GroupLayout(eastSpacerPanel);
        eastSpacerPanel.setLayout(eastSpacerPanelLayout);
        eastSpacerPanelLayout.setHorizontalGroup(
            eastSpacerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        eastSpacerPanelLayout.setVerticalGroup(
            eastSpacerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        getContentPane().add(eastSpacerPanel, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void doneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneBtnActionPerformed
        ExitPage exit = new ExitPage();
        exit.show();
        dispose();
    }//GEN-LAST:event_doneBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BalanceInquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BalanceInquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BalanceInquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BalanceInquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BalanceInquiry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JLabel balanceOutput;
    private javax.swing.JButton doneBtn;
    private javax.swing.JPanel eastSpacerPanel;
    private javax.swing.JLabel jCashLogoMM;
    private javax.swing.JPanel mainMenuPanel;
    private javax.swing.JPanel mainMenuTitlePanel;
    private javax.swing.JPanel southSpacerPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel westSpacerPanel;
    // End of variables declaration//GEN-END:variables
}
