package MainJCashApp;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author "Jahnreil J. Amarillento"
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setIconLogo();
    }
    
    public void setIconLogo() {
            setIconImage(Toolkit.getDefaultToolkit().getImage("src/main/java/Resources/JCash1.png"));
    }
    
    BankAccounts accs = new BankAccounts();
    
    protected void verifyInput(java.awt.event.KeyEvent evt) {
        char value = evt.getKeyChar();

        if (value >= KeyEvent.VK_0 && value <= KeyEvent.VK_9 || value == KeyEvent.VK_BACK_SPACE) {
            acctPinTField.setEditable(true);
            acctNumberTField.setEditable(true);
        } else if ( value == KeyEvent.VK_ENTER ) {
            if (acctPinTField.getText() == null || acctPinTField.getText().trim().isEmpty()) {
                acctPinTField.requestFocusInWindow();
            } else  {
                signinVerify();
            }
        } else {
            acctPinTField.setEditable(false);
            acctNumberTField.setEditable(false);
            JOptionPane.showMessageDialog(this, "Enter numbers 0-9 only");
        }
    }
    
    protected void signinVerify() {  
       acctNumberInput = Integer.parseInt(acctNumberTField.getText());
       System.out.println("Entered actnum: " + acctNumberInput);
       acctPinInput = Integer.parseInt(acctPinTField.getText());
       System.out.println("Entered actpin: " + acctPinInput);
       
       if (accs.getAcct1().verifyAcct(acctNumberInput, acctPinInput) || accs.getAcct1().verifyAcct(acctNumberInput, acctPinInput)) {
           MainMenu mainMenu = new MainMenu();
           mainMenu.show();
           dispose();
       } else {
           JOptionPane.showMessageDialog(this, "Incorrect credentials, please try again");
       }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        screenLogoPanel = new javax.swing.JPanel();
        jCLogo = new javax.swing.JLabel();
        screenLoginPanel = new javax.swing.JPanel();
        bankNumberLabel = new javax.swing.JLabel();
        bankPinLabel = new javax.swing.JLabel();
        acctNumberTField = new javax.swing.JTextField();
        signinBtn = new javax.swing.JButton();
        acctPinTField = new javax.swing.JPasswordField();
        spacerPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(45, 36, 36));
        setPreferredSize(new java.awt.Dimension(545, 700));
        setResizable(false);

        screenLogoPanel.setBackground(new java.awt.Color(45, 36, 36));
        screenLogoPanel.setPreferredSize(new java.awt.Dimension(450, 250));
        screenLogoPanel.setRequestFocusEnabled(false);

        jCLogo.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/730396842197778485/1022840337212911666/JCashLogoFull.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jCLogo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        screenLogoPanel.add(jCLogo);

        getContentPane().add(screenLogoPanel, java.awt.BorderLayout.NORTH);

        screenLoginPanel.setBackground(new java.awt.Color(45, 36, 36));
        screenLoginPanel.setPreferredSize(new java.awt.Dimension(522, 100));

        bankNumberLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        bankNumberLabel.setForeground(new java.awt.Color(224, 192, 151));
        bankNumberLabel.setText("Bank Account Number:");

        bankPinLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        bankPinLabel.setForeground(new java.awt.Color(224, 192, 151));
        bankPinLabel.setText("ENTER 6-Digit PIN : ");

        acctNumberTField.setBackground(new java.awt.Color(224, 192, 151));
        acctNumberTField.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        acctNumberTField.setForeground(new java.awt.Color(45, 36, 36));
        acctNumberTField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                acctNumberTFieldKeyPressed(evt);
            }
        });

        signinBtn.setBackground(new java.awt.Color(92, 61, 46));
        signinBtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        signinBtn.setForeground(new java.awt.Color(224, 192, 151));
        signinBtn.setText("Sign-in");
        signinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinBtnActionPerformed(evt);
            }
        });

        acctPinTField.setBackground(new java.awt.Color(224, 192, 151));
        acctPinTField.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        acctPinTField.setForeground(new java.awt.Color(45, 36, 36));
        acctPinTField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                acctPinTFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout screenLoginPanelLayout = new javax.swing.GroupLayout(screenLoginPanel);
        screenLoginPanel.setLayout(screenLoginPanelLayout);
        screenLoginPanelLayout.setHorizontalGroup(
            screenLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(screenLoginPanelLayout.createSequentialGroup()
                .addGroup(screenLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(screenLoginPanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(screenLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bankNumberLabel)
                            .addComponent(bankPinLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(screenLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acctNumberTField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acctPinTField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(screenLoginPanelLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(signinBtn)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        screenLoginPanelLayout.setVerticalGroup(
            screenLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(screenLoginPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(screenLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bankNumberLabel)
                    .addComponent(acctNumberTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(screenLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bankPinLabel)
                    .addComponent(acctPinTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(signinBtn)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(screenLoginPanel, java.awt.BorderLayout.CENTER);

        spacerPanel.setBackground(new java.awt.Color(45, 36, 36));
        spacerPanel.setPreferredSize(new java.awt.Dimension(522, 150));

        javax.swing.GroupLayout spacerPanelLayout = new javax.swing.GroupLayout(spacerPanel);
        spacerPanel.setLayout(spacerPanelLayout);
        spacerPanelLayout.setHorizontalGroup(
            spacerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );
        spacerPanelLayout.setVerticalGroup(
            spacerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        getContentPane().add(spacerPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private int acctNumberInput, acctPinInput;
    
    private void signinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinBtnActionPerformed
       signinVerify();
    }//GEN-LAST:event_signinBtnActionPerformed

    private void acctNumberTFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_acctNumberTFieldKeyPressed
        verifyInput(evt);
    }//GEN-LAST:event_acctNumberTFieldKeyPressed

    private void acctPinTFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_acctPinTFieldKeyPressed
        verifyInput(evt);
    }//GEN-LAST:event_acctPinTFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acctNumberTField;
    private javax.swing.JPasswordField acctPinTField;
    private javax.swing.JLabel bankNumberLabel;
    private javax.swing.JLabel bankPinLabel;
    private javax.swing.JLabel jCLogo;
    private javax.swing.JPanel screenLoginPanel;
    private javax.swing.JPanel screenLogoPanel;
    private javax.swing.JButton signinBtn;
    private javax.swing.JPanel spacerPanel;
    // End of variables declaration//GEN-END:variables
}
