package MainJCashApp;

import java.awt.Toolkit;

/**
 *
 * @author "Jahnreil J. Amarillento"
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        setIconLogo();
    }

    public void setIconLogo() {
            setIconImage(Toolkit.getDefaultToolkit().getImage("src/main/java/Resources/JCash1.png"));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenuPanel = new javax.swing.JPanel();
        balanceInqBtn = new javax.swing.JButton();
        withdrawaBtn = new javax.swing.JButton();
        DepositBtn = new javax.swing.JButton();
        TransferBtn = new javax.swing.JButton();
        btnSpacer = new javax.swing.JLabel();
        btnSpacer2 = new javax.swing.JLabel();
        mainMenuTitlePanel = new javax.swing.JPanel();
        selOptionLabel = new javax.swing.JLabel();
        jCashLogoMM = new javax.swing.JLabel();
        southSpacerPanel = new javax.swing.JPanel();
        westSpacerPanel = new javax.swing.JPanel();
        eastSpacerPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 800));

        mainMenuPanel.setBackground(new java.awt.Color(45, 36, 36));
        mainMenuPanel.setPreferredSize(new java.awt.Dimension(650, 250));
        mainMenuPanel.setLayout(new java.awt.GridLayout(4, 2, 30, 30));

        balanceInqBtn.setBackground(new java.awt.Color(224, 192, 151));
        balanceInqBtn.setFont(new java.awt.Font("Verdana", 0, 27)); // NOI18N
        balanceInqBtn.setForeground(new java.awt.Color(92, 61, 46));
        balanceInqBtn.setText("Balance Inquiry");
        balanceInqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceInqBtnActionPerformed(evt);
            }
        });
        mainMenuPanel.add(balanceInqBtn);

        withdrawaBtn.setBackground(new java.awt.Color(224, 192, 151));
        withdrawaBtn.setFont(new java.awt.Font("Verdana", 0, 27)); // NOI18N
        withdrawaBtn.setForeground(new java.awt.Color(92, 61, 46));
        withdrawaBtn.setText("Withdrawal");
        withdrawaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawaBtnActionPerformed(evt);
            }
        });
        mainMenuPanel.add(withdrawaBtn);

        DepositBtn.setBackground(new java.awt.Color(224, 192, 151));
        DepositBtn.setFont(new java.awt.Font("Verdana", 0, 27)); // NOI18N
        DepositBtn.setForeground(new java.awt.Color(92, 61, 46));
        DepositBtn.setText("Deposit");
        DepositBtn.setPreferredSize(new java.awt.Dimension(75, 10));
        mainMenuPanel.add(DepositBtn);

        TransferBtn.setBackground(new java.awt.Color(224, 192, 151));
        TransferBtn.setFont(new java.awt.Font("Verdana", 0, 27)); // NOI18N
        TransferBtn.setForeground(new java.awt.Color(92, 61, 46));
        TransferBtn.setText("Transfer");
        TransferBtn.setPreferredSize(new java.awt.Dimension(75, 10));
        mainMenuPanel.add(TransferBtn);
        mainMenuPanel.add(btnSpacer);
        mainMenuPanel.add(btnSpacer2);

        getContentPane().add(mainMenuPanel, java.awt.BorderLayout.CENTER);

        mainMenuTitlePanel.setBackground(new java.awt.Color(45, 36, 36));
        mainMenuTitlePanel.setMinimumSize(new java.awt.Dimension(300, 300));
        mainMenuTitlePanel.setLayout(new java.awt.BorderLayout());

        selOptionLabel.setBackground(new java.awt.Color(45, 36, 36));
        selOptionLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        selOptionLabel.setForeground(new java.awt.Color(224, 192, 151));
        selOptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selOptionLabel.setText("Select an option");
        selOptionLabel.setPreferredSize(new java.awt.Dimension(100, 100));
        mainMenuTitlePanel.add(selOptionLabel, java.awt.BorderLayout.CENTER);

        jCashLogoMM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCashLogoMM.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/730396842197778485/1022840337212911666/JCashLogoFull.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        mainMenuTitlePanel.add(jCashLogoMM, java.awt.BorderLayout.NORTH);

        getContentPane().add(mainMenuTitlePanel, java.awt.BorderLayout.NORTH);

        southSpacerPanel.setBackground(new java.awt.Color(184, 92, 56));

        javax.swing.GroupLayout southSpacerPanelLayout = new javax.swing.GroupLayout(southSpacerPanel);
        southSpacerPanel.setLayout(southSpacerPanelLayout);
        southSpacerPanelLayout.setHorizontalGroup(
            southSpacerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
        );
        southSpacerPanelLayout.setVerticalGroup(
            southSpacerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        getContentPane().add(southSpacerPanel, java.awt.BorderLayout.PAGE_END);

        westSpacerPanel.setBackground(new java.awt.Color(45, 36, 36));

        javax.swing.GroupLayout westSpacerPanelLayout = new javax.swing.GroupLayout(westSpacerPanel);
        westSpacerPanel.setLayout(westSpacerPanelLayout);
        westSpacerPanelLayout.setHorizontalGroup(
            westSpacerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        westSpacerPanelLayout.setVerticalGroup(
            westSpacerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        getContentPane().add(westSpacerPanel, java.awt.BorderLayout.LINE_END);

        eastSpacerPanel.setBackground(new java.awt.Color(45, 36, 36));

        javax.swing.GroupLayout eastSpacerPanelLayout = new javax.swing.GroupLayout(eastSpacerPanel);
        eastSpacerPanel.setLayout(eastSpacerPanelLayout);
        eastSpacerPanelLayout.setHorizontalGroup(
            eastSpacerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        eastSpacerPanelLayout.setVerticalGroup(
            eastSpacerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        getContentPane().add(eastSpacerPanel, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void withdrawaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawaBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_withdrawaBtnActionPerformed

    private void balanceInqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceInqBtnActionPerformed
        // TODO add your handling code here:
        BalanceInquiry balInquiry = new BalanceInquiry();
        balInquiry.show();
        dispose();
    }//GEN-LAST:event_balanceInqBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DepositBtn;
    private javax.swing.JButton TransferBtn;
    private javax.swing.JButton balanceInqBtn;
    private javax.swing.JLabel btnSpacer;
    private javax.swing.JLabel btnSpacer2;
    private javax.swing.JPanel eastSpacerPanel;
    private javax.swing.JLabel jCashLogoMM;
    private javax.swing.JPanel mainMenuPanel;
    private javax.swing.JPanel mainMenuTitlePanel;
    private javax.swing.JLabel selOptionLabel;
    private javax.swing.JPanel southSpacerPanel;
    private javax.swing.JPanel westSpacerPanel;
    private javax.swing.JButton withdrawaBtn;
    // End of variables declaration//GEN-END:variables
}
